In [217]:
import os
os.chdir("D:\\User_Data\\Desktop\\kan-2\\industrial_census\\")

In [373]:
import pandas as pd
new_df=pd.DataFrame()
df=pd.read_excel("empty_csv.xlsx",sheet_name="1954")
df=df.iloc[:23]
df=df.fillna(0)
df["Food and beverage stores_M"]=df["Food and beverage stores_M"]+df["Food and beverage stores_M_1"]
df["Food and beverage stores_F"]=df["Food and beverage stores_F"]+df["Food and beverage stores_F_1"]
df=df.drop(columns=["Food and beverage stores_M_1"])
df=df.drop(columns=["Food and beverage stores_F_1"])
df["Finance and Insurance_M"]=df["Finance and Insurance_M_1"]+df["Finance and Insurance_M_2"]+df["Finance and Insurance_M_3"]
df["Finance and Insurance_F"]=df["Finance and Insurance_F_1"]+df["Finance and Insurance_F_2"]+df["Finance and Insurance_F_3"]
df["Finance and Insurance_M"]=df["Finance and Insurance_M"]+df["Real Estate and Rental and Leasing_M"]
df["Finance and Insurance_F"]=df["Finance and Insurance_F"]+df["Real Estate and Rental and Leasing_F"]
df=df.drop(columns=["Real Estate and Rental and Leasing_M","Real Estate and Rental and Leasing_F"])
df=df.drop(columns=["Finance and Insurance_M_1"])
df=df.drop(columns=["Finance and Insurance_M_2"])
df=df.drop(columns=["Finance and Insurance_M_3"])
df=df.drop(columns=["Finance and Insurance_F_1"])
df=df.drop(columns=["Finance and Insurance_F_2"])
df=df.drop(columns=["Finance and Insurance_F_3"])
df["Arts, entertainment, and recreation_M"]=df["Arts, entertainment, and recreation_M_1"]+df["Arts, entertainment, and recreation_M_2"]+df["Arts, entertainment, and recreation_M_3"]
df["Arts, entertainment, and recreation_F"]=df["Arts, entertainment, and recreation_F_1"]+df["Arts, entertainment, and recreation_F_2"]+df["Arts, entertainment, and recreation_F_3"]
df=df.drop(columns=["Arts, entertainment, and recreation_M_1"])
df=df.drop(columns=["Arts, entertainment, and recreation_M_2"])
df=df.drop(columns=["Arts, entertainment, and recreation_F_1"])
df=df.drop(columns=["Arts, entertainment, and recreation_F_2"])
df=df.drop(columns=["Arts, entertainment, and recreation_M_3"])
df=df.drop(columns=["Arts, entertainment, and recreation_F_3"])
df["Other Retail_M"]=df["Other Retail_M_1"]+df["Other Retail_M"]
df["Other Retail_F"]=df["Other Retail_F_1"]+df["Other Retail_F"]
df["Merchant Wholesale_M"]=df["Merchant Wholesale_M_1"]+df["Merchant Wholesale_M"]
df["Merchant_Wholesale_F"]=df["Merchant Wholesale_F_1"]+df["Merchant Wholesale_F"]
df=df.drop(columns=["Other Retail_M_1","Other Retail_F_1","Merchant Wholesale_M_1","Merchant Wholesale_F_1"])
df=df.drop([16])
df=df.drop([21])
columns=df.columns
for i in range(len(columns[1:])):
    if i%2==1:
        total=df[columns[i]]+df[columns[i+1]]
        new_df[columns[i][:-2]]=total
new_df.index=df[df.columns[0]]
new_df["Coal mining"]=round(new_df["Coal mining"]*((46065+9351)/428))
new_df["Utilities"]=new_df["Utilities"]+new_df["Water"]+new_df["Gas"]
new_df_1954=new_df

In [374]:
import pandas as pd
new_df=pd.DataFrame()
df=pd.read_excel("empty_csv.xlsx",sheet_name="1966")
df=df.iloc[:23]
df=df.fillna(0)
df=df.drop([16])
df=df.drop([21])
df["Finance and Insurance_M"]=df["Finance and Insurance_M"]+df["Real Estate and Rental and Leasing_M"]
df["Finance and Insurance_F"]=df["Finance and Insurance_F"]+df["Real Estate and Rental and Leasing_F"]
df=df.drop(columns=["Real Estate and Rental and Leasing_M","Real Estate and Rental and Leasing_F"])
df["Other Retail_M"]=df["Merchant Wholesale_M"]*(241786/300699)
df["Merchant Wholesale_M"]=df["Merchant Wholesale_M"]*(57105/300699)
columns=df.columns
for i in range(len(columns[1:])):
    if i%2==1:
        total=df[columns[i]]+df[columns[i+1]]
        new_df[columns[i][:-2]]=total
new_df.index=df[df.columns[0]]
new_df["Crop production"]=new_df["Crop production"]*20
new_df["Truck transportation"]=round(new_df["Truck transportation"]*((11883+26844+8510+936)/218854))
new_df["Water transportation"]=round(new_df["Water transportation"]*((7239+643)/1365634))
new_df["Warehousing and storage"]=round(new_df["Warehousing and storage"]*((1292+168)/1179179))
new_df_1966=new_df

In [375]:
import pandas as pd
new_df=pd.DataFrame()
df=pd.read_excel("empty_csv.xlsx",sheet_name="1976")
df=df.iloc[:21]
df=df.fillna(0)
df["Finance and Insurance_M"]=df["Finance and Insurance_M"]+df["Real Estate and Rental and Leasing_M"]
df["Finance and Insurance_F"]=df["Finance and Insurance_F"]+df["Real Estate and Rental and Leasing_F"]
df=df.drop(columns=["Real Estate and Rental and Leasing_M","Real Estate and Rental and Leasing_F"])
columns=df.columns
for i in range(len(columns[1:])):
    if i%2==1:
        total=df[columns[i]]+df[columns[i+1]]
        new_df[columns[i][:-2]]=total
new_df.index=df[df.columns[0]]
new_df_1976=new_df

In [376]:
new_df_1954["Other Transportation"]=new_df_1954["Air transportation"]+new_df_1954["Truck transportation"]+new_df_1954["Water transportation"]+new_df_1954["Transit and ground passenger transportation"]+new_df_1954["Services incidental to transportation"]
new_df_1966["Other Transportation"]=new_df_1966["Air transportation"]+new_df_1966["Truck transportation"]+new_df_1966["Water transportation"]+new_df_1966["Transit and ground passenger transportation"]+new_df_1966["Services incidental to transportation"]
new_df_1976["Other Transportation"]=new_df_1976["Air transportation"]+new_df_1976["Truck transportation"]+new_df_1976["Water transportation"]+new_df_1976["Transit and ground passenger transportation"]+new_df_1976["Services incidental to transportation"]
#new_df_1954["Fishing, hunting, and trapping"]=new_df_1954["Fishing, hunting, and trapping"]+new_df_1954["Logging"]+new_df_1954["Aquaculture"]
new_df_1966["Fishing, hunting, and trapping"]=new_df_1966["Fishing, hunting, and trapping"]+new_df_1966["Logging"]+new_df_1966["Aquaculture"]
new_df_1976["Fishing, hunting, and trapping"]=new_df_1976["Fishing, hunting, and trapping"]+new_df_1976["Logging"]+new_df_1976["Aquaculture"]
new_df_1954["Merchant Wholesale"]=new_df_1954["Merchant Wholesale"]+new_df_1954["Building material and garden equipment and supplies dealers"]+new_df_1954["Motor vehicle and parts dealers"]
new_df_1966["Merchant Wholesale"]=new_df_1966["Merchant Wholesale"]+new_df_1966["Building material and garden equipment and supplies dealers"]+new_df_1966["Motor vehicle and parts dealers"]
new_df_1976["Merchant Wholesale"]=new_df_1976["Merchant Wholesale"]+new_df_1976["Building material and garden equipment and supplies dealers"]+new_df_1976["Motor vehicle and parts dealers"]
new_df_1954["Other Retail"]=new_df_1954["Other Retail"]+new_df_1954["Miscellaneous store retailers"]
new_df_1966["Other Retail"]=new_df_1966["Other Retail"]+new_df_1966["Miscellaneous store retailers"]
new_df_1976["Other Retail"]=new_df_1976["Other Retail"]+new_df_1976["Miscellaneous store retailers"]
new_df_1954["Repair"]=new_df_1954["Automotive repair and maintenance (except car washes)"]
new_df_1966["Repair"]=new_df_1966["Automotive repair and maintenance (except car washes)"]
new_df_1976["Repair"]=new_df_1976["Automotive repair and maintenance (except car washes)"]

new_df_1954=new_df_1954.drop(columns=["Air transportation","Truck transportation","Water transportation","Logging","Motor vehicle and parts dealers","Building material and garden equipment and supplies dealers","Miscellaneous store retailers","Transit and ground passenger transportation","Services incidental to transportation",'Support activities for agriculture and forestry',
 'Support activities for mining','Warehousing and storage','Gasoline stations',
 'Management, administrative, and waste services',
 'Oil and gas extraction','Accommodation and food services',
 'Animal production',
 'Automotive repair and maintenance (except car washes)','Gas',
 'Merchant',
 'Other',
 'Total_manufacturing',
 'Water'])
new_df_1966=new_df_1966.drop(columns=["Air transportation","Truck transportation","Water transportation","Logging","Motor vehicle and parts dealers","Building material and garden equipment and supplies dealers","Aquaculture","Miscellaneous store retailers","Transit and ground passenger transportation","Services incidental to transportation",'Support activities for agriculture and forestry',
 'Support activities for mining','Warehousing and storage','Gasoline stations',
 'Management, administrative, and waste services',
 'Oil and gas extraction','Accommodation and food services',
 'Animal production',
 'Automotive repair and maintenance (except car washes)','Merchant',
 'Other',
 'Total_manufacturing',
 'Total_mining'])
new_df_1976=new_df_1976.drop(columns=["Air transportation","Truck transportation","Water transportation","Logging","Motor vehicle and parts dealers","Building material and garden equipment and supplies dealers","Aquaculture","Miscellaneous store retailers","Transit and ground passenger transportation","Services incidental to transportation",'Support activities for agriculture and forestry',
 'Support activities for mining','Warehousing and storage','Gasoline stations',
 'Management, administrative, and waste services',
 'Oil and gas extraction','Accommodation and food services',
 'Animal production',
 'Automotive repair and maintenance (except car washes)',"total_employee"])

In [378]:
recorded_industry=[[],[],[]]
weighted_average_ratio_1954=[]
for c in range(len(new_df_1954.index)):
    total_ratio_product=0
    total_employee=0
    for i in range(len(ratio_df.index)):
        if ratio_df["industry"][i] in new_df_1954.columns:
            recorded_industry[0].append(ratio_df["industry"][i])
            total_ratio_product=total_ratio_product+ratio_df["male to female ratio"][i]*new_df_1954[ratio_df["industry"][i]][new_df_1954.index[c]]
            total_employee=total_employee+new_df_1954[ratio_df["industry"][i]][new_df_1954.index[c]]
    weighted_average_ratio_1954.append(total_ratio_product/total_employee)
wavg_sex_ratio=pd.DataFrame()
wavg_sex_ratio["male_ratio"]=weighted_average_ratio_1954
wavg_sex_ratio["county"]=new_df_1954.index
wavg_sex_ratio.to_csv("wavg_sex_ratio_1954_6970.csv")

weighted_average_ratio_1966=[]
for c in range(len(new_df_1966.index)):
    total_ratio_product=0
    total_employee=0
    for i in range(len(ratio_df.index)):
        if ratio_df["industry"][i] in new_df_1966.columns:
            recorded_industry[1].append(ratio_df["industry"][i])
            total_ratio_product=total_ratio_product+ratio_df["male to female ratio"][i]*new_df_1966[ratio_df["industry"][i]][new_df_1966.index[c]]
            total_employee=total_employee+new_df_1966[ratio_df["industry"][i]][new_df_1966.index[c]]
    weighted_average_ratio_1966.append(total_ratio_product/total_employee)
wavg_sex_ratio=pd.DataFrame()
wavg_sex_ratio["male_ratio"]=weighted_average_ratio_1966
wavg_sex_ratio["county"]=new_df_1966.index
wavg_sex_ratio.to_csv("wavg_sex_ratio_1966_6970.csv")

weighted_average_ratio_1976=[]
for c in range(len(new_df_1976.index)):
    total_ratio_product=0
    total_employee=0
    for i in range(len(ratio_df.index)):
        if ratio_df["industry"][i] in new_df_1976.columns:
            recorded_industry[2].append(ratio_df["industry"][i])
            total_ratio_product=total_ratio_product+ratio_df["male to female ratio"][i]*new_df_1976[ratio_df["industry"][i]][new_df_1976.index[c]]
            total_employee=total_employee+new_df_1976[ratio_df["industry"][i]][new_df_1976.index[c]]
    weighted_average_ratio_1976.append(total_ratio_product/total_employee)
wavg_sex_ratio=pd.DataFrame()
wavg_sex_ratio["male_ratio"]=weighted_average_ratio_1976
wavg_sex_ratio["county"]=new_df_1976.index
wavg_sex_ratio.to_csv("wavg_sex_ratio_1976_6970.csv")
new_df_1954.to_csv("1954_total_employee.csv")
new_df_1966.to_csv("1966_total_employee.csv")
new_df_1976.to_csv("1976_total_employee.csv")

In [377]:
#ratio_df=pd.read_excel("data.xlsx")
ratio_df=pd.read_csv("total_employee_us_1969-70.csv")
ratio_df["male to female ratio"]=ratio_df["1969+70_sex_ratio"]

In [194]:
wavg_sex_ratio

Index(['male_ratio'], dtype='object')

In [381]:
set(new_df_1954.columns)-set(recorded_industry[0])

set()

In [329]:
ratio_df

,industry,no_gender_1969,male_1969,feamle_1969,male/female ratio1969,no_gender_1970,male_1970,female_1970,male/female ratio1970,diff_1970-1969,male_1969+70,female_1969+70,1969+70_sex_ratio,male to female ratio
0,no_data,10603,0,0,NaN,9750,0,0,NaN,NaN,NaN,NaN,NaN,NaN
1,Neverworked,0,12607,34646,0.363880,0,12134,33208,0.365394,0.001513,24741.0,67854.0,0.364621,0.364621
2,Crop production,0,2664,628,4.242038,0,2507,553,4.533454,0.291416,5171.0,1181.0,4.378493,4.378493
3,Coal mining,0,372,32,11.625000,0,361,30,12.033333,0.408333,733.0,62.0,11.822581,11.822581
4,Construction,0,3624,186,19.483871,0,3557,191,18.623037,-0.860834,7181.0,377.0,19.047745,19.047745
5,Wood product manufacturing,0,478,44,10.863636,0,434,33,13.151515,2.287879,912.0,77.0,11.844156,11.844156
6,Furniture,0,287,94,3.053191,0,279,78,3.576923,0.523732,566.0,172.0,3.290698,3.290698
7,Nonmetallic mineral product manufacturing,0,413,95,4.347368,0,374,88,4.250000,-0.097368,787.0,183.0,4.300546,4.300546
8,Primary metal manufacturing,0,968,94,10.297872,0,867,97,8.938144,-1.359728,1835.0,191.0,9.607330,9.607330
9,Fabricated metal product manufacturing,0,1043,289,3.608997,0,1044,243,4.296296,0.687300,2087.0,532.0,3.922932,3.922932
10,Machinery manufacturing,0,1452,310,4.683871,0,1448,312,4.641026,-0.042845,2900.0,622.0,4.662379,4.662379
11,Eletronic,0,933,629,1.483307,0,928,622,1.491961,0.008655,1861.0,1251.0,1.487610,1.487610
12,Automobile,0,822,94,8.744681,0,754,91,8.285714,-0.458967,1576.0,185.0,8.518919,8.518919
13,Transportation equipment manufacturing,0,892,160,5.575000,0,773,132,5.856061,0.281061,1665.0,292.0,5.702055,5.702055
14,Instrument,0,252,130,1.938462,0,251,121,2.074380,0.135919,503.0,251.0,2.003984,2.003984
15,Miscellaneous,0,207,180,1.150000,0,208,178,1.168539,0.018539,415.0,358.0,1.159218,1.159218
16,Food manufacturing,0,1039,395,2.630380,0,921,309,2.980583,0.350203,1960.0,704.0,2.784091,2.784091
17,Tobaco,0,28,26,1.076923,0,26,28,0.928571,-0.148352,54.0,54.0,1.000000,1.000000
18,Textile,0,439,398,1.103015,0,400,380,1.052632,-0.050383,839.0,778.0,1.078406,1.078406
19,Clothes,0,231,897,0.257525,0,222,818,0.271394,0.013869,453.0,1715.0,0.264140,0.264140
20,Paper,0,494,132,3.742424,0,436,110,3.963636,0.221212,930.0,242.0,3.842975,3.842975
21,"Publishing industries, except Internet",0,696,314,2.216561,0,670,306,2.189542,-0.027018,1366.0,620.0,2.203226,2.203226
22,Chemical manufacturing,0,675,184,3.668478,0,668,200,3.340000,-0.328478,1343.0,384.0,3.497396,3.497396
23,Petroleum,0,165,30,5.500000,0,191,36,5.305556,-0.194444,356.0,66.0,5.393939,5.393939
24,Plastics and rubber products manufacturing,0,290,154,1.883117,0,278,134,2.074627,0.191510,568.0,288.0,1.972222,1.972222
25,Leather,0,136,172,0.790698,0,129,161,0.801242,0.010545,265.0,333.0,0.795796,0.795796
26,Rail transportation,0,484,30,16.133333,0,489,28,17.464286,1.330952,973.0,58.0,16.775862,16.775862
27,Other Transportation,0,1451,287,5.055749,0,1401,255,5.494118,0.438369,2852.0,542.0,5.261993,5.261993
28,Telecommunication,0,421,417,1.009592,0,447,421,1.061758,0.052165,868.0,838.0,1.035800,1.035800
29,Utilities,0,754,106,7.113208,0,737,101,7.297030,0.183822,1491.0,207.0,7.202899,7.202899
30,Merchant Wholesale,0,1548,478,3.238494,0,1523,463,3.289417,0.050923,3071.0,941.0,3.263549,3.263549
31,Food and beverage stores,0,796,1207,0.659486,0,834,1179,0.707379,0.047893,1630.0,2386.0,0.683152,0.683152
32,Other Retail,0,4359,3136,1.389987,0,4290,3047,1.407942,0.017955,8649.0,6183.0,1.398836,1.398836
33,Personal and laundry services,0,359,1674,0.214456,0,307,1513,0.202908,-0.011548,666.0,3187.0,0.208974,0.208974
34,Finance and Insurance,0,1439,1412,1.019122,0,1395,1471,0.948334,-0.070787,2834.0,2883.0,0.983004,0.983004
35,Business,0,594,430,1.381395,0,638,406,1.571429,0.190033,1232.0,836.0,1.473684,1.473684
36,Repair,0,737,88,8.375000,0,652,82,7.951220,-0.423780,1389.0,170.0,8.170588,8.170588
37,Personal and laundry services,0,658,1338,0.491779,0,627,1259,0.498014,0.006236,1285.0,2597.0,0.494802,0.494802
38,"Arts, entertainment, and recreation",0,408,220,1.854545,0,350,202,1.732673,-0.121872,758.0,422.0,1.796209,1.796209
39,Health care and social assistance,0,810,2425,0.334021,0,790,2378,0.332212,-0.001809,1600.0,4803.0,0.333125,0.333125
40,"Religious, grantmaking, civic, professional, a...",0,317,310,1.022581,0,285,289,0.986159,-0.036421,602.0,599.0,1.005008,1.005008
41,Educational services,0,1751,2906,0.602546,0,1691,2898,0.583506,-0.019041,3442.0,5804.0,0.593039,0.593039
42,"Professional, Scientific, and Technical Services",0,659,411,1.603406,0,624,434,1.437788,-0.165618,1283.0,845.0,1.518343,1.518343
43,"Fishing, hunting, and trapping",0,62,8,7.750000,0,79,7,11.285714,3.535714,141.0,15.0,9.400000,9.400000
44,Postal,0,455,104,4.375000,0,422,84,5.023810,0.648810,877.0,188.0,4.664894,4.664894
45,Other Federal,0,756,370,2.043243,0,758,383,1.979112,-0.064131,1514.0,753.0,2.010624,2.010624
46,State,0,314,221,1.420814,0,261,198,1.318182,-0.102633,575.0,419.0,1.372315,1.372315
47,Local,0,726,344,2.110465,0,687,379,1.812665,-0.297800,1413.0,723.0,1.954357,1.954357

In [320]:
new_df_1954.columns

KeyError: 'Aquaculture'

In [328]:
new_df_1954.columns

Index(['Crop production', 'Animal production', 'Logging',
       'Fishing, hunting, and trapping',
       'Support activities for agriculture and forestry',
       'Oil and gas extraction', 'Coal mining',
       'Support activities for mining', 'Construction', 'Food manufacturing',
       'Chemical manufacturing', 'Plastics and rubber products manufacturing',
       'Nonmetallic mineral product manufacturing',
       'Primary metal manufacturing', 'Fabricated metal product manufacturing',
       'Machinery manufacturing', 'Transportation equipment manufacturing',
       'Wood product manufacturing', 'Merchant Wholesale', 'Other Retail',
       'Motor vehicle and parts dealers',
       'Building material and garden equipment and supplies dealers',
       'Food and beverage stores', 'Gasoline stations',
       'Miscellaneous store retailers', 'Air transportation',
       'Rail transportation', 'Water transportation', 'Truck transportation',
       'Transit and ground passenger transportation',
       'Services incidental to transportation', 'Warehousing and storage',
       'Utilities', 'Publishing industries, except Internet',
       'Real Estate and Rental and Leasing',
       'Professional, Scientific, and Technical Services',
       'Management, administrative, and waste services',
       'Educational services', 'Health care and social assistance',
       'Accommodation and food services',
       'Automotive repair and maintenance (except car washes)',
       'Personal and laundry services',
       'Religious, grantmaking, civic, professional, and similar organizations',
       'Gas', 'Water', 'Total_manufacturing', 'Merchant', 'Other', 'Furniture',
       'Eletronic', 'Textile', 'Automobile', 'Instrument', 'Miscellaneous',
       'Tobaco', 'Clothes', 'Paper', 'Petroleum', 'Leather',
       'Finance and Insurance', 'Arts, entertainment, and recreation',
       'Other Transportation'],
      dtype='object')